steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build
    entrypoint: bash
    args:
      - '-c'
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          docker build -t gcr.io/$PROJECT_ID/flatbuffers-builder .
          docker push gcr.io/$PROJECT_ID/flatbuffers-builder
        fi
