name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - name: Build
        run: |
          docker build \
            --tag docker.pkg.github.com/ridedott/flatbuffers-builder-docker/flatbuffers-builder:latest \
            --tag registry.hub.docker.com/ridedott/flatbuffers-builder:latest \
            .
      - env:
          GITHUB_REGISTRY_USERNAME: ${{ github.actor }}
          GITHUB_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN_DOTTBOTT }}
          DOCKER_HUB_REGISTRY_USERNAME:
            ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
          DOCKER_HUB_REGISTRY_PASSWORD:
            ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
        name: Release
        run: |
          # GitHub Package Registry
          echo $GITHUB_REGISTRY_PASSWORD | \
            docker login docker.pkg.github.com \
            --username $GITHUB_REGISTRY_USERNAME \
            --password-stdin
          docker push \
            docker.pkg.github.com/ridedott/flatbuffers-builder-docker/flatbuffers-builder:latest

          # Docker Hub
          echo $DOCKER_HUB_REGISTRY_PASSWORD | \
            docker login registry.hub.docker.com \
            --username $DOCKER_HUB_REGISTRY_USERNAME \
            --password-stdin
          docker push \
            registry.hub.docker.com/ridedott/flatbuffers-builder:latest
